--sdofile(minetest.get_modpath("badplayer").."/api.lua")
--merged into lag's modified mobs mod
--20200122 maikerumine

minetest.register_alias("default:default_apple", "default:apple")
--[[
name = "Sam",
author = "Jordach",
description = "The default skin.",
comment = "Sam Ain't Minecraft",
]]
mobs:register_mob("mobs:Sam", {
	nametag = "Santa Clause Sam",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
    collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 25,
	walk_velocity = 3,
	run_velocity = 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = true,
	peaceful = true,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
	--[[
		on_die = function(self, pos)

		self.object:remove()
		minetest.sound_play({ pos = pos, name = "mobs_spell", gain = 10, max_hear_distance = 500 })
		minetest.sound_play({ pos = pos, name = "lightning_thunder", gain = 10, max_hear_distance = 500 })
		garryghost = minetest.add_entity(self.object:getpos(), "mobs:Nyancat")
		garryghost = minetest.add_entity(self.object:getpos(), "mobs:Nyancat")
		garryghost = minetest.add_entity(self.object:getpos(), "mobs:Nyancat")
		garryghost = minetest.add_entity(self.object:getpos(), "mobs:Nyancat")
		ent = garryghost:get_luaentity()
		
		minetest.add_particlespawner({
			amount = 120,
			time = 2.25,
			minpos = pos,
			maxpos = pos,
			minvel = {x = -2, y = -0.25, z = -2},
			maxvel = {x = 2, y = 2, z = 2},
			minacc = {x = 0, y = 1, z = 0},
			maxacc = {x = 2, y = 10, z = 2},
			minexptime = 0.1,
			maxexptime = 3,
			minsize = 0.5,
			maxsize = 1.0,
			texture = "mobs_blood.png",
		})
		
		
	end,
	]]
})
--mobs:register_spawn("mobs:Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_near("mobs:Sam", "default:stone", 4, -1, 2)
--mobs:register_spawn_bp_near("mobs:Sam", "default:stone", 10, -1, 2)
mobs:spawn({
	name = "mobs:Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})



--[[
name = "Zeg9",
author = "Zeg9",
description = "My own skin.",
]]
mobs:register_mob("mobs:Zeg9", {
	nametag = "Zeg9",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Zeg9", "group:cracky", 14, -1, 29000, 1, -500, 0)
--mobs:register_spawn_bp_near("mobs:Zeg9", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Zeg9",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Alien",
author = "jmf",
]]
mobs:register_mob("mobs:Alien", {
	nametag = "Alien",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Alien", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Alien", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Alien",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Soldier",
author = "jmf",
]]
mobs:register_mob("mobs:Soldier", {
	nametag = "Soldier",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:pick_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Soldier", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Soldier", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Soldier",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "John",
author = "jmf",
]]
mobs:register_mob("mobs:John", {
	nametag = "John",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:sword_wood"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2,
	damage = 2,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:John", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:John", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:John",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Ninja",
author = "jmf",
]]
mobs:register_mob("mobs:Ninja", {
	nametag = "Ninja",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 3,
	walk_velocity = 3,-- 3,
	run_velocity = 3,-- 4,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 50,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Ninja", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Ninja", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Ninja",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Oerkki",
author = "jmf",
]]
mobs:register_mob("mobs:Oerkki", {
	nametag = "Oerkki",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1.2,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Oerkki", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Oerkki", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Oerkki",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Tux",
author = "jmf",
]]
mobs:register_mob("mobs:Tux", {
	nametag = "Tux",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
				"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 1.5,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Tux", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Tux", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Tux",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Black belt",
author = "jmf",
]]
mobs:register_mob("mobs:Blackbelt", {
	nametag = "Blackbelt",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Blackbelt", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Blackbelt", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Blackbelt",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Assassin",
author = "jmf",
]]
mobs:register_mob("mobs:Assassin", {
	nametag = "Assassin",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 10,
	walk_velocity = 3,-- 2,
	run_velocity = 3,-- 5,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 70,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Assassin", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Assassin", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Assassin",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Harry",
author = "jmf",
]]
mobs:register_mob("mobs:Harry", {
	nametag = "Harry",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 5,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Harry", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Harry", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Harry",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Bob",
author = "Chinchow",
]]
mobs:register_mob("mobs:Bob", {
	nametag = "Bob",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:sword_wood"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 0.3,
	run_velocity = 3,-- 1.5,
	damage = 2,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Bob", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Bob", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Bob",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Jannette",
author = "Chinchow",
]]
mobs:register_mob("mobs:Jannette", {
	nametag = "Jannette",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:stick"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1.6,
	run_velocity = 3,-- 2.5,
	damage = 1,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Jannette", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Jannette", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Jannette",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Sheriff",
author = "Chinchow",
]]
mobs:register_mob("mobs:Sheriff", {
	nametag = "Sheriff",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:sword_wood"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2,
	damage = 2,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Sheriff", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Sheriff", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Sheriff",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Sepia Sam",
author = "Hybrid Dog",
]]
mobs:register_mob("mobs:Sepia_Sam", {
	nametag = "Sepia_Sam",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 7,
	walk_velocity = 3,-- 1.3,
	run_velocity = 3,-- 3.9,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Sepia_Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Sepia_Sam", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Sepia_Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Hybrid Sam",
author = "Hybrid Dog",
]]
mobs:register_mob("mobs:Hybrid_Sam", {
	nametag = "Hybrid_Sam",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:pick_wood"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 1.4,
	damage = 2,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Hybrid_Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Hybrid_Sam", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Hybrid_Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Original Sam",
author = "Jordach",
]]
mobs:register_mob("mobs:Original_Sam", {
	nametag = "Original_Sam",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:sword_wood"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2.3,
	damage = 2,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Original_Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Original_Sam", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Original_Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Unnamed",
author = "Hybrid Dog",
]]
mobs:register_mob("mobs:Unnamed", {
	nametag = "Unnamed",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:pick_stone"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Unnamed", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Unnamed", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Unnamed",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "VanessaE",
author = "Jordach",
comment = "Actually based from an old picture",
]]
mobs:register_mob("mobs:VanessaE", {
	nametag = "VanessaE",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 25,
	walk_velocity = 3,-- 0.6,
	run_velocity = 3,-- 1.8,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:VanessaE", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:VanessaE", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:VanessaE",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Female Sam",
author = "Jordach",
]]
mobs:register_mob("mobs:Female_Sam", {
	nametag = "Mrs. Santa Clause",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_mrs_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:pick_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1.7,
	run_velocity = 3,-- 2.5,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Female_Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Female_Sam", "default:stone", 10, -1, 2)
mobs:spawn({
	name = "mobs:Female_Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})


--[[
name = "Battlefield 3 Soldier",
author = "Jordach",
]]
mobs:register_mob("mobs:Battlefield_3_Soldier", {
	nametag = "Battlefield_3_Soldier",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:pick_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 4,
	walk_velocity = 3,-- 2.5,
	run_velocity = 3,-- 7,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Battlefield_3_Soldier", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Battlefield_3_Soldier", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Battlefield_3_Soldier",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Smooth Sam",
author = "Jordach",
]]
mobs:register_mob("mobs:Smooth_Sam", {
	nametag = "Smooth_Sam",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 3,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Smooth_Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Smooth_Sam", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Smooth_Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Celeron55",
author = "Jordach",
comment = "Based on a picture from the wiki.",
]]
mobs:register_mob("mobs:Celeron55", {
	nametag = "Celeron55",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 7,
	walk_velocity = 3,-- 1.3,
	run_velocity = 3,-- 3.5,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Celeron55", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Celeron55", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Celeron55",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Tuxedo Sam",
author = "Jordach",
]]
mobs:register_mob("mobs:Tuxedo_Sam", {
	nametag = "Tuxedo_Sam",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1.5,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 60,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Tuxedo_Sam", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Tuxedo_Sam", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Tuxedo_Sam",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Iron Man MK. 7",
author = "Jordach",
]]
mobs:register_mob("mobs:Iron_Man_MK_7", {
	nametag = "Iron_Man_MK_7",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:pick_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 12,
	walk_velocity = 3,-- 2,
	run_velocity = 3,-- 3,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 65,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Iron_Man_MK_7", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Iron_Man_MK_7", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Iron_Man_MK_7",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Jordach",
author = "Jordach",
]]
mobs:register_mob("mobs:Jordach", {
	nametag = "Jordach",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:axe_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Jordach", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Jordach", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Jordach",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Max",
author = "Stuart Jones",
]]
mobs:register_mob("mobs:Max", {
	nametag = "Max",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 10,
	walk_velocity = 3,-- 2,
	run_velocity = 3,-- 4,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Max", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Max", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Max",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Slenderman",
author = "prof_turbo",
]]
mobs:register_mob("mobs:Slenderman", {
	nametag = "Slenderman",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 25,
	walk_velocity = 3,-- 0.5,
	run_velocity = 3,-- 1.5,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Slenderman", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Slenderman", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:Slenderman",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "Strange Killer",
author = "prof_turbo",
]]
mobs:register_mob("mobs:Strange_Killer", {
	nametag = "Strange_Killer",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:sword_stone"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 2,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:Strange_Killer", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:Strange_Killer", "default:stone", 10, -1, 2)
--function mobs:register_spawn(name, nodes, max_light, min_light, chance, active_object_count, max_height, min_height, spawn_func)
--[[
mobs:spawn({
	name = "mobs:Strange_Killer",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "jojoa1997",
author = "jojoa1997",
]]
mobs:register_mob("mobs:jojoa1997", {
	nametag = "jojoa1997",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["mobs:sword_steel"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 5,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 6,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:jojoa1997", "group:cracky", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:jojoa1997", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:jojoa1997",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]

--[[
name = "DrakeOfDuty",
author = "jmfApprentice Prince",
]]
mobs:register_mob("mobs:DrakeOfDuty", {
	nametag = "DrakeOfDuty",
	type = "monster", docile_by_day = true,
	pathfinding = 1,
	hp_min = 25,	
	hp_max = 55,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.x",
	textures = {"character_santa.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:stick"].inventory_image,
			},
	visual_size = {x=1.0, y=1.0},
	makes_footstep_sound = true,
	view_range = 5,
	walk_velocity = 3,-- 1,
	run_velocity = 3,-- 6,
	damage = 4,
	drops = {
		{name = "mobs:cooked_rat",
		chance = 1,
		min = 1,
		max = 2,},
		{name = "default:coal_lump",
		chance = 4,
		min = 1,
		max = 1,},
		{name = "default:snow",
		chance = 2,
		min = 1,
		max=1,
		},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 0,
	on_rightclick = nil,
	attack_type = "dogfight",
	--lifetimer=300,
	animation = {
		speed_normal = 30,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		random = "hohoho",
		--attack = "rocks",
		war_cry = "grr",
		--shoot_attack = "rocks",
		--damage = "rocks",
		--jump = "rocks",
		death = "grr",
	},
	attacks_monsters = false,
	peaceful = false,
	group_attack = true,
	step = 1,
	jump = true,
	fear_height = 10,
	
})
--mobs:register_spawn("mobs:DrakeOfDuty", "group:snappy", 6, 1, 120000, 1, 500, 0)
--mobs:register_spawn_bp_near("mobs:jojoa1997", "default:stone", 10, -1, 2)
--[[
mobs:spawn({
	name = "mobs:DrakeOfDuty",
	nodes = {"group:cracky", "group:stone"},
	neighbors = {"air"},
	min_light = 0,
	max_light = 6,
	interval = 30,
	chance = 170000,
	active_object_count = 1,
	min_height = -1,
	max_height = 1000,
	day_toggle = nil,
	on_spawn = nil,
	on_map_load = nil,
})
]]
--[[
if minetest.setting_get("log_mods") then
	minetest.log("action", "Maikerumine's BadPlayer mobs locked and loaded")
end
]]
