--mobs_esmobs v1.3
--maikerumine
--made for Extreme Survival game
--License for code is WTFPL




mobs:register_mob("mobs_esmobs:dirtmons", {
	type = "monster",
	hp_min = 30,
	hp_max = 50,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_dirtmons.png"}},
	--visual_size = {x=3.5, y=2.8},
	makes_footstep_sound = true,
	view_range = 24,
	follow = "flowers:viola",--swap out type randomly for server players"flowers:tulip","flowers:rose","flowers:geranium","flowers:dandelion_yellow","flowers:dandelion_white",
	walk_velocity = 2.5,
	run_velocity = 3.8,
	damage = 3.7,
	reach = 2,
	drops = {
		{name = "default:dirt",
		chance = 1,
		min = 1,
		max = 2,},

		{name = "flowers:viola",
		chance = 10,
		min = 0,
		max = 1,},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 6,
	on_rightclick = nil,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	sounds = {
		war_cry = "mobs_stone",
		death = "mobs_death2",
		attack = "mobs_stone_attack",
		},
})

---------------------------------------
--EXTREME SURVUVAL MOBS
---------------------------------------
-- Spider by AspireMint (fishyWET (CC-BY-SA 3.0 license for texture)
mobs:register_mob("mobs_esmobs:spider", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	pathfinding = true,
	damage = 3,
	hp_min = 40,
	hp_max = 80,
	armor = 100,
	collisionbox = {-0.9, -0.01, -0.7, 0.7, 0.6, 0.7},
	visual = "mesh",
	mesh = "mobs_spider.x",
	textures = {{
		"mobs_spider.png"
	}},
	visual_size = {x=3,y=3},
	makes_footstep_sound = false,
	sounds = {
		random = "mobs_spider",
		attack = "mobs_spider",
	},
	walk_velocity = 1.7,
	run_velocity = 3.3,
	jump = true,
	view_range = 15,
	floats = 0,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
    drops = {
		{name = "farming:string",
		chance = 1, min = 1, max = 5,},
		{name = "mobs:meat_raw",
		chance = 1, min = 0, max = 1,},
	},
	water_damage = 5,
	lava_damage = 50,
	light_damage = 0,
	fear_height = 14,
	animation = {
		speed_normal = 15,		speed_run = 15,
		stand_start = 1,		stand_end = 1,
		walk_start = 20,		walk_end = 40,
		run_start = 20,			run_end = 40,
		punch_start = 50,		punch_end = 90,
	},
})


--Applmons by maikerumine
mobs:register_mob("mobs_esmobs:applmons", {
	type = "monster",
	hp_min = 20,
	hp_max = 28,
	collisionbox = {-0.4, -0.3, -0.4, 0.4, 0.6, 0.4},
	visual = "mesh",
	mesh = "mobs_dungeon_master.b3d",
	textures = {{"mobs_applmons.png"}},
	visual_size = {x=0.6, y=0.3},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 3,
	run_velocity = 3.6,
	damage = 3,
	drops = {
		{name = "default:apple",
		chance = 4,
		min = 1,
		max = 3,},
	},

	sounds = {
		random = "mobs_rat",
		--random = "Fuse",
		explode = "explo",
		attack = "Fuse",
		war_cry  = "Fuse",
	},


	armor = 100,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 3,
	light_damage = 0,
	jump = true,
	jump_height = 8,
	fall_damage = 0,
	fall_speed = -5,
	stepheight = 2.1,
	fear_height = 6,
	on_rightclick = nil,
	--attack_type = "dogfight",
	attack_type = "explode",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 19,
		walk_start = 20,
		walk_end = 35,
		run_start = 30,
		run_end = 40,
		punch_start = 36,
		punch_end = 48,
	}
})


--Herobrine's Bloody Ghost by Lovehart and maikerumine  http://minetest.fensta.mobslaced.net/#author=lovehart
mobs:register_mob("mobs_esmobs:herobrines_bloody_ghost", {
	type = "monster",
	hp_min = 320,
	hp_max = 340,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.b3d",
	textures = {{"mobs_herobrines_bloody_ghost.png"}},
	visual_size = {x=1, y=1.0},
	makes_footstep_sound = true,
	view_range = 19,
	walk_velocity = 1.8,
	run_velocity = 3.6,
	damage = 10,
	drops = {
		{name = "default:mese",
		chance = 7,
		min = 1,
		max = 4,},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 210,
	lava_damage = 50,
	light_damage = 150,
	fear_height = 30,
	on_rightclick = nil,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 19,
		walk_start = 20,
		walk_end = 35,
		run_start = 30,
		run_end = 40,
		punch_start = 36,
		punch_end = 48,
	}
})

--Phoenix from NSSM and bat from minetest defense merged into this
--mobs:register_spawn("mobs_esmobs:phoenix", {"air","air"}, 6, -1, 170000, 1, 100)
mobs:register_mob("mobs_esmobs:paniki", {
	type = "monster",
	hp_max = 40,
	hp_min = 20,
	damage = 1,
	collisionbox = {-0.15, -0.2, -0.15, 0.15, 0.2, 0.15},
	visual = "mesh",
	mesh = "phoenix.b3d",  --paniki from minetest defense
	textures = {{"mobs_paniki.png"}},  --paniki from minetest defense
	visual_size = {x=0.2, y=0.2},
	view_range = 90,
	lifetimer = 500,
	floats=1,
	rotate = 270,
	walk_velocity = 0.5,
	run_velocity = 2.0,
  fall_speed = 2,
  stepheight = 1,
  sounds = {
		--random = "phoenix",
		attack = "mobs_rat",
		random = "mobs_rat",
		distance = 15,
	},
	damage = 2,
	--jump = true,
	drops = {
		{name = "mobs:feather",
		chance = 1,
		min = 1,
		max = 1,},
		{name = "mobs:meat_raw",
		chance = 1,
		min = 1,
		max = 1,},
		{name = "default:gold_lump",
		chance = 6,
		min = 1,
		max = 2,},
		{name = "mobs:leather",
		chance = 1, min = 0, max = 1},
	},
	armor = 60,
	--drawtype = "side",
	water_damage = 5,
	lava_damage = 40,
	light_damage = 10,
	--fear_height = 70,
	on_rightclick = nil,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	fly = true,
	--attack_type = "shoot",
	attack_type = "dogfight",
		--arrow = "throwing:arrow_entity",
		arrow = "mobs:fireball",
		--arrow = "tnt:tnt_ent",
		reach = 1,
		shoot_interval = 1.25,

	animation = {
		speed_normal = 22,
		speed_run = 25,
		stand_start = 220,
		stand_end = 280,
		walk_start = 30,
		walk_end = 59,
		run_start = 60,
		run_end = 89,
		punch_start = 60,
		punch_end = 89,
		--dattack_start = 60,
		--dattack_end = 89,
	}
})

--Phoenix from NSSM and bat from minetest defense merged into this
--mobs:register_spawn("mobs_esmobs:phoenix", {"air","air"}, 6, -1, 170000, 1, 100)
mobs:register_mob("mobs_esmobs:phoenix", {
	type = "monster",
	hp_max = 60,
	hp_min = 50,
	damage = 2,
	collisionbox = {-0.65, -0.4, -0.65, 0.65, 0.4, 0.65},
	visual = "mesh",
	mesh = "phoenix.b3d",  --paniki from minetest defense
	textures = {{"mobs_paniki.png"}},  --paniki from minetest defense
	visual_size = {x=4, y=4},
	view_range = 90,
	lifetimer = 500,
	floats=1,
	rotate = 270,
	walk_velocity = 2.5,
	run_velocity = 6.5,
  fall_speed = 1,
  stepheight = 3,
  sounds = {
		--random = "phoenix",
		attack = "mobs_fireball",
		random = "Fuse",
		shoot_attack = "mobs_fireball",
		distance = 15,
	},
	damage = 2,
	--jump = true,
	drops = {

		{name = "mobs:feather",
		chance = 1,
		min = 1,
		max = 1,},
		{name = "mobs_animal:chicken",
		chance = 1,
		min = 5,
		max = 6,},
		{name = "default:gold_lump",
		chance = 6,
		min = 10,
		max = 20,},
	},
	armor = 60,
	--drawtype = "side",
	water_damage = 5,
	lava_damage = 0,
	light_damage = 10,
	--fear_height = 70,
	on_rightclick = nil,
	fly = true,
	attack_type = "shoot",
	pathfinding = true,
	--attack_type = "dogfight",
		--arrow = "throwing:arrow_entity",
		arrow = "mobs:fireball",
		--arrow = "tnt:tnt_ent",
		reach = 1,
		shoot_interval = 1.25,

	animation = {
		speed_normal = 22,
		speed_run = 25,
		stand_start = 220,
		stand_end = 280,
		walk_start = 30,
		walk_end = 59,
		run_start = 60,
		run_end = 89,
		punch_start = 60,
		punch_end = 89,
		--dattack_start = 60,
		--dattack_end = 89,
	}
})

mobs:register_mob("mobs_esmobs:bomber", {
	type = "monster",
	hp_max = 60,
	hp_min = 50,
	collisionbox = {-1.65, -1.4, -1.65, 1.65, 0.4, 1.65},
	visual = "mesh",
	mesh = "phoenix.b3d",  --paniki from minetest defense
	textures = {{"mobs_bomber.png"}},  --paniki from minetest defense made into a plane
	visual_size = {x=10, y=3},
	view_range = 90,
	lifetimer = 500,
	floats=1,
	rotate = 270,
	walk_velocity = 2.5,
	run_velocity = 6.5,
  fall_speed = 1,
  stepheight = 3,
  sounds = {
		random = "explo",
		shoot_attack = "mobs_stonemonster",
		attack = "Fuse",
		distance = 45,
	},
	damage = 2,
	--jump = true,
	drops = {
		{name = "default:stone",
		chance = 1,
		min = 7,
		max = 8,},
		{name = "mobs:feather",
		chance = 1,
		min = 1,
		max = 1,},
		{name = "mobs_esmobs:stonemons",
		chance = 1,
		min = 1,
		max = 1,},

	},
	armor = 60,
	--drawtype = "side",
	water_damage = 5,
	lava_damage = 0,
	light_damage = 10,
	on_rightclick = nil,
	fly = true,
	attack_type = "shoot",
	pathfinding = true,
	--attack_type = "dogfight",
		--arrow = "default:lava_flowing",
		--arrow = "mobs_esmobs:bonebullet",
		--arrow = "mobs_esmobs:tnt2_ent",
		--arrow = "mobs_esmobs:bone_monster",
		arrow = "mobs_esmobs:stonemons",
		--arrow = "mobs_esmobs:smbullet",
		reach = 1,
		shoot_interval = 10,

	animation = {
		speed_normal = 22,
		speed_run = 25,
		stand_start = 220,
		stand_end = 223,
		walk_start = 30,
		walk_end = 30,
		run_start = 60,
		run_end = 60,
		punch_start = 87,
		punch_end = 89,
		--dattack_start = 60,
		--dattack_end = 89,
	}
})

-- Bone Monster by maikerumine
mobs:register_mob("mobs_esmobs:bonemons", {
	type = "monster",
	passive = false,
	attack_type = "dogshoot",
	pathfinding = true,
	arrow = "mobs:bonebullet",
	--reach = 1,
	shoot_interval = 1.5,
	shoot_offset = 2,
	damage = 2,
	hp_min = 17,
	hp_max = 35,
	armor = 90,
	collisionbox = {-0.5, -1.5, -0.5, 0.5, 0.5, 0.5},
	--visual = "node",
	visual = "mesh",
	mesh = "bone_monster.x",
	textures = {{
	"mobs_bonemons.png"
	}},
	visual_size = {x=0.9,y=0.9},
	makes_footstep_sound = true,
	sounds = {
		random = "default_gravel_footstep",
	},
	walk_velocity = 1.5,
	run_velocity = 4,
	view_range = 15,
	jump = true,
	jump_height = 8,
	fall_damage = 0,
	fall_speed = -0.5,
	stepheight = 3,
	fear_height = 30,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	floats = 1,
	drops = {
		{name = "bones:bones",
		chance = 1, min = 3, max = 5,},
		{name = "default:steelblock",
		chance = 3, min = 0, max = 2,},
		{name = "mobs:feather",
		chance = 1, min = 3, max = 9,},

	},
	water_damage = 4,
	lava_damage = 4,
	light_damage = 4,
		animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},

})

-- axe (weapon)
mobs:register_arrow(":mobs:bonebullet", {
	visual = "sprite",
	visual_size = {x = 0.3, y = 0.3},
	textures = {"bones_front.png"},
	velocity = 7,

	-- direct hit, no fire... just plenty of pain
	hit_player = function(self, player)
		player:punch(self.object, 1.0, {
			full_punch_interval = 1.0,
			damage_groups = {fleshy = 4},
		}, nil)
	end,

	hit_mob = function(self, player)
		player:punch(self.object, 1.0, {
			full_punch_interval = 1.0,
			damage_groups = {fleshy = 7},
		}, nil)
	end,
})



mobs:register_mob("mobs_esmobs:icemons", {
	type = "monster",
	hp_min = 80,
	hp_max = 110,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_icemons.png"}},
	--visual_size = {x=3.5, y=2.8},
	makes_footstep_sound = true,
	view_range = 14,
	walk_velocity = 2.0,
	run_velocity = 2.9,
	damage = 4,
	sounds = {
		random = "mobs_stonemonster",
	},
	drops = {
		{name = "default:ice",
		chance = 1,
		min = 3,
		max = 6,},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 30,
	on_rightclick = nil,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 37,
		punch_end = 49,
	}

})

mobs:register_mob("mobs_esmobs:snowmons", {
	type = "monster",
	hp_min = 69,
	hp_max = 112,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_snowmons.png"}},
	--visual_size = {x=5.5, y=2.8},
	makes_footstep_sound = true,
	view_range = 14,
	walk_velocity = 1.0,
	run_velocity = 2.0,
	damage = 5,
	sounds = {
		random = "mobs_stonemonster",
	},
	drops = {
		{name = "default:snow",
		chance = 1,
		min = 3,
		max = 6,},
	},
	armor = 80,
	drawtype = "front",
	water_damage = 20,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 3,
	on_rightclick = nil,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 37,
		punch_end = 49,
	}

})

mobs:register_mob("mobs_esmobs:watermons", {
	type = "monster",
	hp_min = 35,
	hp_max = 75,
	collisionbox = {-0.3, -1.0, -0.3, 0.3, 0.8, 0.3},
	visual = "mesh",
	mesh = "3d_armor_character.b3d",
	textures = {{"mobs_watermons.png",
			"3d_armor_trans.png",
				minetest.registered_items["default:pick_wood"].inventory_image,
			}},
	visual_size = {x=1, y=1},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 0.9,
	run_velocity = 1.8,
	damage = 1,
	drops = {
		{name = "default:water_flowing",
		chance = 1,
		min = 0,
		max = 2,},
		{name = "bucket:bucket_empty",
		chance = 8,
		min = 0,
		max = 1,},

	},
	armor = 80,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 3,
	on_rightclick = nil,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
	peaceful = false,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		random = "mobs_stonemonster",
	},
})


mobs:register_mob("mobs_esmobs:blue", {
	type = "monster",
	hp_min = 30,
	hp_max = 50,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_blue.png"}},
	--visual_size = {x=3.5, y=2.8},
	makes_footstep_sound = true,
	view_range = 24,
	follow = "flowers:rose",--swap out type randomly for server players"flowers:tulip","flowers:rose","flowers:geranium","flowers:dandelion_yellow","flowers:dandelion_white",
	walk_velocity = 1.5,
	run_velocity = 2.8,
	damage = 3.7,
	drops = {
		{name = "default:dirt",
		chance = 1,
		min = 1,
		max = 2,},

		{name = "flowers:rose",
		chance = 10,
		min = 0,
		max = 1,},
	},
	armor = 75,
	drawtype = "front",
	water_damage = 20,
	lava_damage = 40,
	light_damage = 1,
	fear_height = 6,
	on_rightclick = nil,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	sounds = {
		war_cry = "mobs_stone",
		death = "mobs_death2",
		attack = "mobs_stone_attack",
		},
})

-- Stone Monster by PilzAdam
mobs:register_mob("mobs_esmobs:stonemons", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	pathfinding = true,
	group_attack = true,
		replace_rate = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_offset = -1,
	peaceful = false,
	damage = 6,
	hp_min = 82,
	hp_max = 105,
	armor = 80,
	collisionbox = {-0.4, -1, -0.4, 0.4, 0.9, 0.4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{
		"mobs_stone_monster.png^[colorize:#FF0000:130"
	}},
	--visual_size = {x=3, y=2.6},
	makes_footstep_sound = true,
	sounds = {
		random = "mobs_stone_attack",
	},
	walk_velocity = 0.5,
	run_velocity = 1.6,
	jump = true,
	floats = 1,
	jump_height = 17,
	fall_damage = 0,
	fall_speed = -13.5,
	view_range = 13,
	drops = {
		{name = "default:stone",
		chance = 2, min = 0, max = 2,},
		{name = "default:iron_lump",
		chance=5, min=0, max=5,},
		{name = "default:coal_lump",
		chance=3, min=0, max=5,},
	},
	water_damage = 5,
	lava_damage = 0,
	light_damage = 1,
	fear_height = 33,
	animation = {
		speed_normal = 15,		speed_run = 15,
		stand_start = 0,		stand_end = 14,
		walk_start = 15,		walk_end = 38,
		run_start = 40,			run_end = 43,
		punch_start = 43,		punch_end = 43,
	},
})


--NOTE: ALWAYS PUT THE REGISTER_SPAWN BELOW THE REGISTER_ENTITY!!!!!
--function mobs:spawn_specific(name, nodes, neighbors, min_light, max_light, interval, chance, active_object_count, min_height, max_height)
--function (mod_name_here):spawn_specific(name, nodes, neighbors, min_light, max_light, interval, chance, active_object_count, min_height, max_height)
mobs:register_spawn("mobs_esmobs:spider", {"default:stone" ,"default:cobble","group:crumbly", "group:cracky", "group:choppy", "group:snappy"}, 6, -1, 3000, 1, 3000)
mobs:register_spawn("mobs_esmobs:applmons", {"default:stone" ,"default:cobble","group:crumbly", "group:cracky", "group:choppy", "group:snappy"}, 6, -1, 3000, 1, -70)
mobs:register_spawn("mobs_esmobs:herobrines_bloody_ghost", {"default:stone","default:desert_sand","nether:brick", "bedrock2:bedrock"}, 4, -1, 9000, 1, -6030)
mobs:register_spawn("mobs_esmobs:bonemons", {"default:stone_with_iron","bones:bones","mobs_esmobs:bones", "bedrock2:bedrock","default:stone","es:strange_grass","es:aiden_grass"},6, -1, 8000, 1, 3000)
mobs:register_spawn("mobs_esmobs:icemons", {"default:ice"}, 5, -1, 18000, 1, 3100)
mobs:register_spawn("mobs_esmobs:snowmons", {"default:snow","default:snowblock","default:snow_block", "default:dirt_with_snow"}, 5, -1, 6000, 1, 3000)
mobs:register_spawn("mobs_esmobs:watermons", {"default:water_source","default:water_flowing"}, 5, -1, 18000, 1, -120)
mobs:register_spawn("mobs_esmobs:blue", {"default:dirt_with_grass","default:stone", "default:stonebrick","default:cobble","es:strange_grass","es:aiden_grass","group:crumbly"}, 5, -1, 6000, 1, -100)
mobs:register_spawn("mobs_esmobs:stonemons", {"default:stone","bedrock2:bedrock"}, 5, -1, 8000, 1, -500)
mobs:register_spawn("mobs_esmobs:dirtmons", {"default:dirt_with_grass","default:stone", "default:stonebrick","default:cobble","es:strange_grass","es:dry_dirt","group:crumbly"}, 5, -1, 5000, 1, 3000)
--mobs:register_spawn("mobs_esmobs:phoenix",{"air"}, 4,-1, 16000, 1, 90,false)
--mobs:register_spawn("mobs_esmobs:paniki", {"air", "default:stone_with_coal", "default:stone"}, 5,-1, 14000, 1, 20,false)
--mobs:register_spawn("mobs_esmobs:bomber", {"air"}, 4,-1, 18000, 1, 90,false)
